export const ROLES = {
    SUPER_ADMIN: 'SUPER_ADMIN',
    ADMIN: 'ADMIN',
    MANAGER: 'MANAGER',
    TEAM_LEADER: 'TEAM_LEADER',
    COUNSELOR: 'COUNSELOR',
    CUSTOMER_SUPPORT: 'CUSTOMER_SUPPORT'
};
